/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteRouteImport } from './routes/_hub/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubKnowledgeRouteImport } from './routes/_hub/knowledge'
import { Route as HubMcpIndexRouteImport } from './routes/_hub/mcp.index'
import { Route as HubAuthIndexRouteImport } from './routes/_hub/auth.index'
import { Route as HubMcpMcpIdRouteImport } from './routes/_hub/mcp.$mcpId'
import { Route as HubAuthAuthIdRouteImport } from './routes/_hub/auth.$authId'

const HubRouteRoute = HubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubKnowledgeRoute = HubKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubMcpIndexRoute = HubMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubAuthIndexRoute = HubAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubMcpMcpIdRoute = HubMcpMcpIdRouteImport.update({
  id: '/mcp/$mcpId',
  path: '/mcp/$mcpId',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubAuthAuthIdRoute = HubAuthAuthIdRouteImport.update({
  id: '/auth/$authId',
  path: '/auth/$authId',
  getParentRoute: () => HubRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof HubKnowledgeRoute
  '/auth/$authId': typeof HubAuthAuthIdRoute
  '/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/auth': typeof HubAuthIndexRoute
  '/mcp': typeof HubMcpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge': typeof HubKnowledgeRoute
  '/auth/$authId': typeof HubAuthAuthIdRoute
  '/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/auth': typeof HubAuthIndexRoute
  '/mcp': typeof HubMcpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hub': typeof HubRouteRouteWithChildren
  '/_hub/knowledge': typeof HubKnowledgeRoute
  '/_hub/auth/$authId': typeof HubAuthAuthIdRoute
  '/_hub/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/_hub/auth/': typeof HubAuthIndexRoute
  '/_hub/mcp/': typeof HubMcpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge'
    | '/auth/$authId'
    | '/mcp/$mcpId'
    | '/auth'
    | '/mcp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/knowledge' | '/auth/$authId' | '/mcp/$mcpId' | '/auth' | '/mcp'
  id:
    | '__root__'
    | '/'
    | '/_hub'
    | '/_hub/knowledge'
    | '/_hub/auth/$authId'
    | '/_hub/mcp/$mcpId'
    | '/_hub/auth/'
    | '/_hub/mcp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRouteRoute: typeof HubRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/knowledge': {
      id: '/_hub/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof HubKnowledgeRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/mcp/': {
      id: '/_hub/mcp/'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof HubMcpIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/auth/': {
      id: '/_hub/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof HubAuthIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/mcp/$mcpId': {
      id: '/_hub/mcp/$mcpId'
      path: '/mcp/$mcpId'
      fullPath: '/mcp/$mcpId'
      preLoaderRoute: typeof HubMcpMcpIdRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/auth/$authId': {
      id: '/_hub/auth/$authId'
      path: '/auth/$authId'
      fullPath: '/auth/$authId'
      preLoaderRoute: typeof HubAuthAuthIdRouteImport
      parentRoute: typeof HubRouteRoute
    }
  }
}

interface HubRouteRouteChildren {
  HubKnowledgeRoute: typeof HubKnowledgeRoute
  HubAuthAuthIdRoute: typeof HubAuthAuthIdRoute
  HubMcpMcpIdRoute: typeof HubMcpMcpIdRoute
  HubAuthIndexRoute: typeof HubAuthIndexRoute
  HubMcpIndexRoute: typeof HubMcpIndexRoute
}

const HubRouteRouteChildren: HubRouteRouteChildren = {
  HubKnowledgeRoute: HubKnowledgeRoute,
  HubAuthAuthIdRoute: HubAuthAuthIdRoute,
  HubMcpMcpIdRoute: HubMcpMcpIdRoute,
  HubAuthIndexRoute: HubAuthIndexRoute,
  HubMcpIndexRoute: HubMcpIndexRoute,
}

const HubRouteRouteWithChildren = HubRouteRoute._addFileChildren(
  HubRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRouteRoute: HubRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
