/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteRouteImport } from './routes/_hub/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubMcpIndexRouteImport } from './routes/_hub/mcp.index'
import { Route as HubKnowledgeIndexRouteImport } from './routes/_hub/knowledge/index'
import { Route as HubAuthIndexRouteImport } from './routes/_hub/auth.index'
import { Route as HubMcpMcpIdRouteImport } from './routes/_hub/mcp.$mcpId'
import { Route as HubKnowledgeNewRouteImport } from './routes/_hub/knowledge/new'
import { Route as HubKnowledgeBrowseRouteImport } from './routes/_hub/knowledge/browse'
import { Route as HubKnowledgeIdRouteImport } from './routes/_hub/knowledge/$id'
import { Route as HubAuthAuthIdRouteImport } from './routes/_hub/auth.$authId'

const HubRouteRoute = HubRouteRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubMcpIndexRoute = HubMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubKnowledgeIndexRoute = HubKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubAuthIndexRoute = HubAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubMcpMcpIdRoute = HubMcpMcpIdRouteImport.update({
  id: '/mcp/$mcpId',
  path: '/mcp/$mcpId',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubKnowledgeNewRoute = HubKnowledgeNewRouteImport.update({
  id: '/knowledge/new',
  path: '/knowledge/new',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubKnowledgeBrowseRoute = HubKnowledgeBrowseRouteImport.update({
  id: '/knowledge/browse',
  path: '/knowledge/browse',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubKnowledgeIdRoute = HubKnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => HubRouteRoute,
} as any)
const HubAuthAuthIdRoute = HubAuthAuthIdRouteImport.update({
  id: '/auth/$authId',
  path: '/auth/$authId',
  getParentRoute: () => HubRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$authId': typeof HubAuthAuthIdRoute
  '/knowledge/$id': typeof HubKnowledgeIdRoute
  '/knowledge/browse': typeof HubKnowledgeBrowseRoute
  '/knowledge/new': typeof HubKnowledgeNewRoute
  '/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/auth': typeof HubAuthIndexRoute
  '/knowledge': typeof HubKnowledgeIndexRoute
  '/mcp': typeof HubMcpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$authId': typeof HubAuthAuthIdRoute
  '/knowledge/$id': typeof HubKnowledgeIdRoute
  '/knowledge/browse': typeof HubKnowledgeBrowseRoute
  '/knowledge/new': typeof HubKnowledgeNewRoute
  '/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/auth': typeof HubAuthIndexRoute
  '/knowledge': typeof HubKnowledgeIndexRoute
  '/mcp': typeof HubMcpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hub': typeof HubRouteRouteWithChildren
  '/_hub/auth/$authId': typeof HubAuthAuthIdRoute
  '/_hub/knowledge/$id': typeof HubKnowledgeIdRoute
  '/_hub/knowledge/browse': typeof HubKnowledgeBrowseRoute
  '/_hub/knowledge/new': typeof HubKnowledgeNewRoute
  '/_hub/mcp/$mcpId': typeof HubMcpMcpIdRoute
  '/_hub/auth/': typeof HubAuthIndexRoute
  '/_hub/knowledge/': typeof HubKnowledgeIndexRoute
  '/_hub/mcp/': typeof HubMcpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$authId'
    | '/knowledge/$id'
    | '/knowledge/browse'
    | '/knowledge/new'
    | '/mcp/$mcpId'
    | '/auth'
    | '/knowledge'
    | '/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$authId'
    | '/knowledge/$id'
    | '/knowledge/browse'
    | '/knowledge/new'
    | '/mcp/$mcpId'
    | '/auth'
    | '/knowledge'
    | '/mcp'
  id:
    | '__root__'
    | '/'
    | '/_hub'
    | '/_hub/auth/$authId'
    | '/_hub/knowledge/$id'
    | '/_hub/knowledge/browse'
    | '/_hub/knowledge/new'
    | '/_hub/mcp/$mcpId'
    | '/_hub/auth/'
    | '/_hub/knowledge/'
    | '/_hub/mcp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRouteRoute: typeof HubRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/mcp/': {
      id: '/_hub/mcp/'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof HubMcpIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/knowledge/': {
      id: '/_hub/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof HubKnowledgeIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/auth/': {
      id: '/_hub/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof HubAuthIndexRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/mcp/$mcpId': {
      id: '/_hub/mcp/$mcpId'
      path: '/mcp/$mcpId'
      fullPath: '/mcp/$mcpId'
      preLoaderRoute: typeof HubMcpMcpIdRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/knowledge/new': {
      id: '/_hub/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof HubKnowledgeNewRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/knowledge/browse': {
      id: '/_hub/knowledge/browse'
      path: '/knowledge/browse'
      fullPath: '/knowledge/browse'
      preLoaderRoute: typeof HubKnowledgeBrowseRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/knowledge/$id': {
      id: '/_hub/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof HubKnowledgeIdRouteImport
      parentRoute: typeof HubRouteRoute
    }
    '/_hub/auth/$authId': {
      id: '/_hub/auth/$authId'
      path: '/auth/$authId'
      fullPath: '/auth/$authId'
      preLoaderRoute: typeof HubAuthAuthIdRouteImport
      parentRoute: typeof HubRouteRoute
    }
  }
}

interface HubRouteRouteChildren {
  HubAuthAuthIdRoute: typeof HubAuthAuthIdRoute
  HubKnowledgeIdRoute: typeof HubKnowledgeIdRoute
  HubKnowledgeBrowseRoute: typeof HubKnowledgeBrowseRoute
  HubKnowledgeNewRoute: typeof HubKnowledgeNewRoute
  HubMcpMcpIdRoute: typeof HubMcpMcpIdRoute
  HubAuthIndexRoute: typeof HubAuthIndexRoute
  HubKnowledgeIndexRoute: typeof HubKnowledgeIndexRoute
  HubMcpIndexRoute: typeof HubMcpIndexRoute
}

const HubRouteRouteChildren: HubRouteRouteChildren = {
  HubAuthAuthIdRoute: HubAuthAuthIdRoute,
  HubKnowledgeIdRoute: HubKnowledgeIdRoute,
  HubKnowledgeBrowseRoute: HubKnowledgeBrowseRoute,
  HubKnowledgeNewRoute: HubKnowledgeNewRoute,
  HubMcpMcpIdRoute: HubMcpMcpIdRoute,
  HubAuthIndexRoute: HubAuthIndexRoute,
  HubKnowledgeIndexRoute: HubKnowledgeIndexRoute,
  HubMcpIndexRoute: HubMcpIndexRoute,
}

const HubRouteRouteWithChildren = HubRouteRoute._addFileChildren(
  HubRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRouteRoute: HubRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
