// This file is generated by icon spritesheet generator

export const iconNames = [
  "warning",
  "wallet",
  "user-shield",
  "trash",
  "swipe",
  "support",
  "shield-check",
  "settings",
  "home",
  "google",
  "github",
  "file",
  "doc",
  "code",
  "check",
  "authfile",
  "ai",
] as const

export type IconName = typeof iconNames[number]
